# Generated by Django 4.1.3 on 2023-07-23 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rasgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('coste', models.IntegerField(default=0)),
                ('vida', models.IntegerField(default=0)),
                ('armadura', models.IntegerField(default=0)),
                ('resistenciaMagica', models.IntegerField(default=0)),
                ('dano', models.IntegerField(default=0)),
                ('velocidadDeAtaque', models.FloatField(default=0)),
                ('chanceDeCritico', models.FloatField(default=0)),
                ('multiplicadorDeCritico', models.FloatField(default=0)),
                ('manaInicial', models.IntegerField(default=0)),
                ('mana', models.IntegerField(default=0)),
                ('rango', models.IntegerField(default=0)),
                ('habilidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='unidades.habilidad')),
                ('rasgos', models.ManyToManyField(to='unidades.rasgo')),
            ],
        ),
    ]
